### PR TITLE
Bump `ain:1.8.0` `whale:latest` `playground:latest`

### PR DESCRIPTION
**Pull request by monstrobishi**
#### What kind of PR is this?:

/kind chore

#### What this PR does / why we need it:
Fix defichain dependencies

#### Which issue(s) does this PR fixes?:

Fixes #

### CODE REVIEW

**Review by jingyi2811 — DISMISSED** [review]

**Comment by fuxingloh** [comment]
https://github.com/DeFiCh/salmon/blob/main/.github/workflows/e2e/docker-compose.yml

need to update these too

**Comment by fuxingloh** [comment]
`whale: 0.8.0` is still getting deployed only `whale: 0.7.0` is live in ocean

**Comment by monstrobishi** [comment]
@fuxingloh so should I wait for 0.8.0 or downgrade to 0.7.0

**Comment by fuxingloh** [comment]
> @fuxingloh so should I wait for 0.8.0 or downgrade to 0.7.0

downgrade to `v0.7` first since that will be live for at least 2-4 weeks.

**Review by jingyi2811 — APPROVED** [review]

**Review by fuxingloh — APPROVED** [review]

**Pull request merged**
