### PR TITLE
Set whale version to v0

### PR DESCRIPTION
**Pull request by monstrobishi**
#### What kind of PR is this?:

/kind chore

#### What this PR does / why we need it:

Set whale version to v0

#### Which issue(s) does this PR fixes?:

Fixes #

### CODE REVIEW

**Review by fuxingloh — DISMISSED** [review]

**Review by fuxingloh — APPROVED** [review]

**Comment by fuxingloh** [comment]
Need to set the routing to `v0` in https://github.com/DeFiCh/salmon/blob/fad03deac2c78fc94d46e92cb47f05ab6314a4e3/.github/workflows/e2e/docker-compose.yml#L70

**Review by canonbrother — APPROVED** [review]

**Comment by monstrobishi** [comment]
@fuxingloh I compared with wallet it also has:
`- "traefik.http.routers.whale.rule=PathPrefix(`/v{[0-9]+}.{[0-9]+}/regtest/`)"`

So I'm wondering how it does it

**Comment by monstrobishi** [comment]
I'm guessing it's the dot (.) in the middle, will try and change that rule

**Comment by monstrobishi** [comment]
Ok figured it out I just had to set `WHALE_VERSION` in docker compose

**Pull request merged**
